[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".wgetrc"]
    type = "file"
    url = "https://raw.githubusercontent.com/dotphiles/dotphiles/master/wget/wgetrc"
    refreshPeriod = "168h"
[".zi"]
    type = "archive"
    url = "https://github.com/z-shell/zi/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
