[colors]
background = '#0D1926'
foreground = '#B4E1FD'
selection-background = '#0B1621'
selection-foreground = '#ffffff'
cursor = '#B4E1FD'
black = '#363636'
red = '#FF0883'
green = '#83FF08'
yellow = '#FF8308'
blue = '#0883FF'
magenta = '#8308FF'
cyan = '#08FF83'
white = '#B6B6B6'
light_black = '#424242'
light_red = '#FF1E8E'
light_green = '#8EFF1E'
light_yellow = '#FF8E1E'
light_blue = '#1E8EFF'
light_magenta = '#8E1EFF'
light_cyan = '#1EFF8E'
light_white = '#C2C2C2'
