description = "macOS productivity and desktop utilities"
workstation_only = true
client_only = true

[darwin]
pre_brew = ["mas"]
cask = [
  "raycast",
  "rectangle-pro",
  "daisydisk",
  "ubar",
  "obsidian",
  "dropshare",
]
mas = [
  "1198176727",  # Controller for HomeKit
  "1622835804",  # Kagi for Safari extension
]
